# Generated by Django 5.2.7 on 2026-02-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_school_address_remove_school_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('aadhaar', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('birth_place', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('admission_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('last_std', models.CharField(max_length=20)),
                ('last_school', models.CharField(max_length=200)),
                ('admission_std', models.CharField(max_length=20)),
                ('remark', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
        ),
    ]
