# Generated by Django 5.2.7 on 2026-02-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('PRINCIPAL', 'Principal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
