# Generated by Django 5.2.7 on 2026-02-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role_alter_school_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='code',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_active',
        ),
    ]
