# Generated by Django 5.2.7 on 2026-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_school_address_remove_school_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
