# Generated by Django 5.2.7 on 2026-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_school_address_school_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(default=True, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
